application: celestial-feat-356
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /test-api
  static_dir: test-api
- url: /.*
  script: edtech.application

libraries:
- name: jinja2
  version: latest

