application: edtech-2013
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: templates/static
- url: /.*
  script: controller.application

libraries:
- name: jinja2
  version: latest

